Fist animations tweak and two handed pistol
freedoom/freedoom pull request #1193
Opened 2023-11-11 06:48 UTC by Anonysussy

Tweaking the fist animations and gave the pistol sprite an extra hand

2023-11-11 07:28 UTC, mc776 approved these changes

2023-11-11 07:31 UTC, mc776 commented
Just gave it a try and I was *not* expecting this to be as much of an improvement as it was. Stuff just feels so much more snappy and solid with this.

I thought the left fist in the B frame would have that awful "blinking in and out of existence" effect but it's low enough not to be a problem at all.

2023-11-11 07:33 UTC, mc776 commented
Btw feel free to add yourself to the CREDITS file for spriting work... I think the format should be pretty self-explanatory at this point

2023-11-11 07:53 UTC, mc776 requested changes

2023-11-11 07:53 UTC, mc776 commented on buildcfg.txt
> +PISGB0  -125	-82
Consider increasing B y offset to -87 and C to -92, and the flash to -74. The animation looks a lot smoother.

2023-11-11 08:08 UTC, mc776 commented
Can I ask what the rationale for getting rid of the back lights in the flash frame is? Personally I don't particularly care either way (tbh I'd get rid of those lights altogether if it were up to me), just wondering.

2023-11-11 08:11 UTC, Anonysussy commented
It's mostly due to an alignment issue I found when I testing out the pistol for myself where the flash lines up but the lights didn't

2023-11-11 15:44 UTC, mc776 commented
![DOOM01](https://github.com/freedoom/freedoom/assets/24984517/f04c7a49-6a43-47da-80ba-4f3c71a54abd)

Here's the current version... I really can't see how this got messed up just by adding the second hand.

2023-11-11 16:38 UTC, mc776 commented
Looking at the pictures again and I think the real problem with the flash is that I overdid the bright part over the front sight post, so the entire thing looks lower than it actually is.

Can you replace the PISFA0 with this one?
![pisfa0](https://github.com/freedoom/freedoom/assets/24984517/db087145-d288-4702-b042-10b970ecdd97)

Here's a preview of how it looks, with both the old and new B frame:
![_](https://github.com/freedoom/freedoom/assets/24984517/74656a41-59fa-46b5-bd29-6f1c0db30fe1)

2023-11-11 17:13 UTC, mc776 commented
Actually, no, use this one instead, the flash really is overlapping the gun too much:
![pisfa0](https://github.com/freedoom/freedoom/assets/24984517/36267742-7b9a-41ad-ae01-ce8e3fca621b)
![prev](https://github.com/freedoom/freedoom/assets/24984517/c6b15f97-67b3-4f86-8f02-63d1704c3168)


(Note that this requires moving the PISFA0 offset up by 2 - -67 for the current, -72 for my suggested offsets.)

2023-11-11 17:32 UTC, selliott512 commented
Looks good. I was initially concerned that this would take up too much screen real estate, but that seems to not be an issue in game given the way it is cropped.

2023-11-11 18:27 UTC, mc776 commented
One more little enhancement I'd like to suggest: visible trigger pull on B frame.
![pisgb0](https://github.com/freedoom/freedoom/assets/24984517/381f70c0-1080-47e0-847f-80e486c61715)

2023-11-11 18:51 UTC, mc776 commented
B frame with trigger pull:
![pisgb0](https://github.com/freedoom/freedoom/assets/24984517/0b4e3214-3cf7-44d3-b933-c36373a7262d)

C frame with the corners near the fingers smoothed out:
![pisgc0](https://github.com/freedoom/freedoom/assets/24984517/330a43fd-cad6-445c-946f-03866cb998c0)

2023-11-11 19:02 UTC, mc776 commented
C frame with slightly smoother corners on the slide and a bit more shadow around the index finger:
![pisgc0](https://github.com/freedoom/freedoom/assets/24984517/5cb3b3fb-b828-4e1c-b8aa-884c6885abcc)

2023-11-12 03:59 UTC, mc776 commented
Any comment about the requested changes?

2023-11-12 04:07 UTC, Anonysussy commented
Can I position the pistol a bit higher? It would probably help highlight the 2nd hand a bit more

2023-11-12 17:59 UTC, mc776 commented
I think these offsets work pretty well:
```
PISFA0  -144	-70
PISGA0  -125	-82
PISGB0  -125	-85
PISGC0  -124	-84
```

2023-11-12 18:14 UTC, mc776 commented
Did you see the updated flash I posted earlier? It actually fixes some proportional problems in the current one.
![pisfa0](https://github.com/freedoom/freedoom/assets/24984517/ab1f3322-e2ec-4be3-a8e6-ee55b35c8c4d)

With this and the recent gun frame updates my suggestion goes to
```
PISFA0  -144	-71
PISGA0  -125	-82
PISGB0  -125	-85
PISGC0  -124	-84
```

2023-11-13 09:08 UTC, Anonysussy commented
I've been considering going with
PISFA0 -144 -66
PISGA0 -125 -84
PISGB0 -125 -80
PISGC0 -124 -88
The reload animations of yours is smoother I must say but the firing animations is kinda weak, I also doubt many people would go out of their way to fire the pistol once at a time to see the reload animations, so I don't really bother with it that much, either way, should I go with your suggestion or going with my own offset?

2023-11-13 15:46 UTC, mc776 commented
Let's go with mine.

2023-11-14 02:36 UTC, mc776 approved these changes

2023-11-14 02:58 UTC, merged