New sounds for the BFG and plasma rifle
freedoom/freedoom pull request #1294
Opened 2024-01-29 03:36 UTC by uhbooh

Made by MoonDeLaAxel and I, from CC0 sounds.

Sources
https://opengameart.org/content/space-laser
https://opengameart.org/content/doomsday-laser-cannon-sound-effect
https://opengameart.org/content/synthesized-explosion

2024-01-29 08:24 UTC, mc776 commented
I like them and they definitely work well, though they need to be much louder to sound right ingame.

Poking around on bart's OGA profile and they look legit so far... i'm not missing anything, am I?

2024-01-29 08:27 UTC, mc776 commented
If we're about to post a release, my opinion is that this PR should be deferred and the release should not be delayed because of this.

However, I'm not going to add the deferred tag because if the release is delayed for totally unrelated reasons and all outstanding issues are addressed on this PR, then it should be merged.

2024-01-29 17:30 UTC, mc776 commented
While testing #1296 I'd accidentally used a wad that had both that sound and these ones and yeah they are definitely not loud enough...

2024-01-30 03:57 UTC, uhbooh commented
Yeah I'm aware that the sounds aren't very loud. My skills with audacity are not the best, but I'll try to fix them sometime soon.

2024-04-03 09:46 UTC, Snoucher requested changes
I just noticed that in chocolate doom dsrxplod.wav doesn't play to it's end, which creates a noticeable cut off in the audio. We should probably do something about it before we merge it.

2024-10-29 21:47 UTC, Xindage commented
so we anyone else wanna point out if you like this one or not? i'm inclined to close this one.

2024-10-30 06:16 UTC, mc776 commented
> I just noticed that in chocolate doom dsrxplod.wav doesn't play to it's end, which creates a noticeable cut off in the audio. We should probably do something about it before we merge it.

In vanilla the sound only plays as long as the actor emitting it exists.

The BFG ball animation has six frames at 8 tics each, so that's 48 tics or 48/35= 1371 milliseconds.

This sound is over 3 seconds long, about 2.5 seconds before it's too quiet to hear.

2025-04-21 23:11 UTC, uhbooh commented
Well it has been over a year since I worked on this, but if enough people like these sounds I can finish them. My Audacity skills have improved quite a bit so I can make these sounds fit in Freedoom better.

2025-06-16 23:56 UTC, closed without merging